### ISSUE TITLE
is this ready for near term production use?

### ISSUE THREAD

**Issue by johnwillyn** [crcn/mesh.js#265]
Hi Craig,
I have been following the development of mesh for about a month (since you pointed it out on the sift list).  Can you give any guidance on current readiness for a near term production use (by an outside party)?  Are the basic interfaces stable?  I noticed you moved a lot of specific bus implementations into 'packages', and I suspect you will continue evolving those more aggressively, but are the core Bus and Response interfaces 'stable' at this point.

This seems like (another) really useful core tech.

Thanks,
JohnL

**Comment by crcn** [comment]
Yep,  Mesh is used pretty heavily now in a few production applications, and the API is stable. However, there still might be breaking changes in the future - the repo is setup to facilitate that possibility. 

Mesh follows [semantic versioning](http://semver.org/) - `major.minor.patch` versions. Any `major` change going forward will first be teed up as a warning (`minor` change) so that you have enough time to upgrade. This is how React, and Ember versions their repos.

`packages` exist primarily for maintainability. They're extra plugins you can use with mesh, and I'll continue to add more as needed. 

Documentation, videos, and blog posts are also in the pipeline.
